# Generated by Django 2.2.6 on 2019-10-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('poster', models.ImageField(upload_to=None)),
                ('about', models.CharField(max_length=500)),
                ('rait', models.FloatField()),
                ('rait_out', models.FloatField()),
                ('director', models.CharField(max_length=50)),
                ('stars', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
                ('add_date', models.DateField()),
                ('release', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
