# Generated by Django 2.2.5 on 2019-10-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmlib', '0002_auto_20191014_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='kinopois_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(),
        ),
    ]
