# Generated by Django 2.2.6 on 2019-10-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmlib', '0004_auto_20191016_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='rait_out',
            new_name='rait_home',
        ),
    ]
