# Generated by Django 2.2.6 on 2019-10-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmlib', '0005_auto_20191016_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
